import { Theme } from 'theme-ui';

export const theme: Theme = {
  useColorSchemeMediaQuery: false,
  useLocalStorage: false,
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fonts: {
    body: '"Josefin Sans", sans-serif',
    heading: '"SJosefin Sans", sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: [10, 16, 24, 32, 48, 64, 96],
  fontWeights: {
    light: 200,
    body: 400,
    heading: 600,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  initialColorModeName: 'unitedStates',
  colors: {
    text: '#3c3b6e',
    background: '#fff',
    primary: '#B22234',
    secondary: '#B22234',
    muted: '#efefef',
    modes: {
      argentina: {
        text: '#80AAD7',
        background: '#fff',
        primary: '#F4C05F',
        secondary: '#F4C05F',
        muted: '#efefef',
      },
      bahamas: {
        text: '#FFC72C',
        background: '#00778B',
        primary: '#000',
        secondary: '#000',
        muted: '#f6f6f6',
      },
      china: {
        text: '#fff',
        background: '#EB3223',
        primary: '#f6b40e',
        secondary: '#f6b40e',
        muted: '#505050',
      },
      india: {
        text: '#F29E49',
        background: '#fff',
        primary: '#529642',
        secondary: '#000D7E',
        muted: '#f6f6f6',
      },
      israel: {
        text: '#0038b8',
        background: '#FFFFFF',
        primary: '#0038b8',
        secondary: '#b1b1b1',
        muted: '#efefef',
      },
      italy: {
        text: '#008C45',
        background: '#fff',
        primary: '#CD212A',
        secondary: '#CD212A',
        muted: '#f6f6f6',
      },
      jamaica: {
        text: '#449847',
        background: '#000',
        primary: '#F8D147',
        secondary: '#F8D147',
        muted: '#f6f6f6',
      },
      japan: {
        text: '#AD2332',
        background: '#fff',
        primary: '#AD2332',
        secondary: '#808080',
        muted: '#efefef',
      },
      qatar: {
        text: '#8A1538',
        background: '#fff',
        primary: '#8A1538',
        secondary: '#808080',
        muted: '#f6f6f6',
      },
      southAfrica: {
        text: '#000',
        background: '#007749',
        primary: '#FFB81C',
        secondary: '#E03C31',
        muted: '#f6f6f6',
      },
      ukraine: {
        text: '#ffd700',
        background: '#0057b7',
        primary: '#ffd700',
        secondary: '#ececec',
        muted: '#000',
      },
      zaire: {
        text: '#fff',
        background: '#5CC73B',
        primary: '#FFFD54',
        secondary: '#FFFD54',
        muted: '#EB3223',
      },
    },
  },
  sizes: ['0px', '1rem', '2rem', '3rem', '4rem', '8rem', '10rem', '14rem'],
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
    },
    h1: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 5,
    },
    h2: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 4,
    },
    h3: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 3,
    },
    h4: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 2,
    },
    h5: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 1,
    },
    h6: {
      color: 'text',
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      fontSize: 0,
    },
    p: {
      color: 'text',
      fontFamily: 'body',
      fontWeight: 'body',
      lineHeight: 'body',
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
      '&:hover': {
        color: 'muted',
      },
    },
    pre: {
      fontFamily: 'monospace',
      overflowX: 'auto',
      code: {
        color: 'inherit',
      },
    },
    code: {
      fontFamily: 'monospace',
      fontSize: 'inherit',
    },
    table: {
      width: '100%',
      borderCollapse: 'separate',
      borderSpacing: 0,
    },
    th: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    td: {
      textAlign: 'left',
      borderBottomStyle: 'solid',
    },
    img: {
      maxWidth: '100%',
    },
  },
};
